
services:

  user-service-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-app
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env.docker
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=campus_eventhub_hasura_postgres
      - DB_PORT=5432
      - RABBITMQ_HOST=campus_eventhub_rabbitmq
    networks:
      - campus_eventhub_network

networks:
  campus_eventhub_network:
    external: true
    name: campus_eventhub_shared_network

volumes:
  user_service_mysql_data:

